services:
  app:
    build: ./
    ports:
      - 8001:80
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: laravel
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_HOST=db
